language: node_js
node_js:
  - 10

jobs:
  include:
    - stage: deploy
      deploy:
        provider: npm
        email: james@notjam.es
        api_key: $NPM_TOKEN
        on:
          tags: true
          repo: imnotjames/whois-servers
    - stage: deploy
      deploy:
        provider: npm
        email: james@notjam.es
        api_key: $NPM_TOKEN
        tag: next
        on:
          branch: master
          repo: imnotjames/whois-servers
